### ISSUE TITLE
License for nHAPI.

### ISSUE THREAD

**Issue by ssinfod** [nHapiNET/nHapi#119]
Hello Usualdosage. 

I see that you are the new maintainer of nHAPI, this is great news !
I'm also using nHAPI since a few weeks. 
Let me know if I can help.

Regarding this ticket. I think this project should have a license.
I sugget to have a MIT or BSD license.

What do you think ?

**Comment by Usualdosage** [comment]
Hi ssinfod. According to the information I've seen in the files, it's licensed under the MPL/GPL v 1.1. This appears to come from the original port from java. As much as I'd like to put it under the MIT license, I don't think I'm legally allowed to change it. 

> /// <summary>The contents of this file are subject to the Mozilla Public License Version 1.1 
/// (the "License"); you may not use this file except in compliance with the License. 
/// You may obtain a copy of the License at http://www.mozilla.org/MPL/ 
/// Software distributed under the License is distributed on an "AS IS" basis, 
/// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the 
/// specific language governing rights and limitations under the License. 
/// The Original Code is "NormativeDatabase.java".  Description: 
/// "Point of access to a copy of the HL7 normative database" 
/// The Initial Developer of the Original Code is University Health Network. Copyright (C) 
/// 2001.  All Rights Reserved. 
/// Contributor(s): ______________________________________. 
/// Alternatively, the contents of this file may be used under the terms of the 
/// GNU General Public License (the  “GPL”), in which case the provisions of the GPL are 
/// applicable instead of those above.  If you wish to allow use of your version of this 
/// file only under the terms of the GPL and not to allow others to use your version 
/// of this file under the MPL, indicate your decision by deleting  the provisions above 
/// and replace  them with the notice and other provisions required by the GPL License.  
/// If you do not delete the provisions above, a recipient may use your version of 
/// this file under either the MPL or the GPL. 
/// </summary>

**Comment by Usualdosage** [comment]
Added MPL 2.0 for review: https://github.com/nHapiNET/nHapi/pull/120
