### ISSUE TITLE
Cannot get the diagnosis description in ORM_O01

### ISSUE THREAD

**Issue by dinhnam2901** [nHapiNET/nHapi#213]
Hi @all !

Describe the bug:
I cannot get the diagnosis description from the ORM_O01 message by using nhapi.

```csharp
var ourPipeParser = new PipeParser();
var hl7Message = ourPipeParser.Parse(hl7Msg);
string examReason = data.GetORDER().ORDER_DETAIL.GetDG1().DiagnosisDescription.Value; // return an empty string
Platform.Log(LogLevel.Error, "---- ExamReason: " + examReason);
```

But, I using the hl7 tool and it getting ok.
![GetDescriptionByTool](https://user-images.githubusercontent.com/20145650/119759808-12ef9480-bed3-11eb-8136-74790e36fcbc.PNG)

And, there is my hl7 message:

```
MSH|^~\&|RIS|ABC|||1234|1148|ORM^O01|1234|P|2.3||||||UNICODE UTF-8
PID|1||1234||nguyen^a b c||12345678|F|||patient address test
PV1||O|||||||||||||||||1234
DG1||||test diagnosis description
ORC|NW|1234|1234||||||1234|||1234^Tran^c d e
OBR|1|1234|1234|2394^Chup Xquang abc [ben trai]
```

Environmental Details:
 - OS:  Windows Server 2019
 - Target .Net Framework
 - Version 4.0
 - HL7 Version: 2.3

**Comment by milkshakeuk** [comment]
@dinhnam2901 what version of nHapi does this relate to?

**Comment by milkshakeuk** [comment]
Having done a brief inspection, it looks like your message is nonstandard (some of the segments are in the wrong order), if you move the DG1 to the end so it's your last segment then it will become standard and the code you supplied show include a value.

```
MSH|^~\&|RIS|ABC|||1234|1148|ORM^O01|1234|P|2.3||||||UNICODE UTF-8
PID|1||1234||nguyen^a b c||12345678|F|||patient address test
PV1||O|||||||||||||||||1234
ORC|NW|1234|1234||||||1234|||1234^Tran^c d e
OBR|1|1234|1234|2394^Chup Xquang abc [ben trai]
DG1||||test diagnosis description
```

Hapi test panel also shows this, because `DG1` came before `OCR` and `OBR` it makes them all look like they are nonstandard.

![image](https://user-images.githubusercontent.com/1087376/119802228-497ade80-bed6-11eb-9bb0-77cc3a3b565c.png)

The order of the segments is important in hl7.

**Comment by dinhnam2901** [comment]
I see.
Thank you so much!

**Comment by milkshakeuk** [comment]
let me know if that fixes your issue.

**Comment by dinhnam2901** [comment]
Yeah, I was corrected as same as your suggestion, and it work correctly!
