### ISSUE TITLE
Include the optional `LongName` attribute in the XML encoded output.

### ISSUE THREAD

**Issue by laxmi-lal-menaria** [nHapiNET/nHapi#301]
I am new to HL7 parser, I need to parse and save data to Database. 

I have tried to use NHAPI and I found that its has all segments with their descriptions while debugging. I need these description with the segments position or any alternative to get them?

i.e. PID.5 ->  Patient Name

![image](https://user-images.githubusercontent.com/570114/171907031-055d0e98-1bc4-44ac-8629-efda97bb1238.png)

**Comment by milkshakeuk** [comment]
@lmenaria can you provide more info on what output you're looking for? An example?

**Comment by lmenaria** [comment]
I would need these actual name with the values.

![image](https://user-images.githubusercontent.com/570114/172207562-f7c8a5c9-553f-4980-94a2-0bcba4548fa7.png)

Or is there any mapping file where from I get these actual naming for my database.

Please help me on that part.

**Comment by milkshakeuk** [comment]
Having had a look at the specification for the xml encoded hl7 v2 there is an `optional` attribute that can be used called `LongName` which should contain the information you want; this is currently not included in the xml encoded output likely because its optional and also it would make the output very large.

It would look like this:

```xml
...
<OBX>
    <OBX.1 LongName='Set ID - OBX'>1</OBX.1>
    <OBX.2 LongName='Value Type'>ST</OBX.2>
    <OBX.3 LongName='Observation Identifier'>
        <CE.1 LongName='identifier'>9804-6</CE.1>
        <CE.2 LongName='text'>Weight</CE.2>
        <CE.3 LongName='name of coding system'>LN</CE.3>
    </OBX.3>
    <OBX.5 LongName='Observation Value'>74</OBX.5>
    <OBX.6 LongName='Units'>
        <CE.1 LongName='identifier'>kg</CE.1>
    </OBX.6>
    <OBX.11 LongName='Observation Result Status'>F</OBX.11>
</OBX>
...
```

Technically this could be done as an enhancement to the `DefaultXmlParser` to `optionally` include the `LongName` attribute, assuming the long name is currently available during encoding, feel free to create a pull request for this.

In regards to if there is a mapping file ... you can get all those long names from the xml schemas (xsd files) for each version from [hl7 product page](https://www.hl7.org/implement/standards/product_brief.cfm?product_id=213).

**Comment by laxmilal-menaria** [comment]
Thanks, I will review the code base and try to add this optional property. 

Meanwhile if anyone who is willing to add the new property quickly, this will let me a lot.

**Comment by lmenaria** [comment]
Created a pull request: @ https://github.com/nHapiNET/nHapi/pull/308

**Comment by milkshakeuk** [comment]
@laxmi-lal-menaria any updates on your PR?

**Comment by milkshakeuk** [comment]
@laxmi-lal-menaria this change is in the latest `3.2.0` version.
