### ISSUE TITLE
V23 ORM Message Not Parsing Right

### ISSUE THREAD

**Issue by thestephenstanton** [nHapiNET/nHapi#35]
If you have an 2.3 ORM^O01 and run it through PipeParser.Parse() it will return back a GenericMessage.V23 IMessage.  It only happens for 2.3.  It does however work if you pass in ORM^O01^ORM_O01 as the type.  But this should not be required.

**Comment by Eric-Cadwell** [comment]
I had to investigate some other issues and hit this as well. Since I was investigating I went to see why this was happening.

It looks like being provided only the first two segments it's doing a lookup from the EventMap. However the 2.3 EventMap has five entries for ORM_O01. This causes it to come back with a type name of "ORM_O01,OMD_O01,OMN_O01,OMS_O01,RDO_O01" which isn't found in the class lookup. It looks like 2.3.1 works fine but only has one entry for ORM_O01 as the key (left hand side)

2.3:
ORM_O01	ORM_O01
ORM_O01	OMD_O01
ORM_O01	OMN_O01
ORM_O01	OMS_O01
ORM_O01	RDO_O01

2.3.1
ORM_O01	ORM_O01
OMD_O01	ORM_O01
OMN_O01	ORM_O01
OMS_O01	ORM_O01
RDO_O01	ORM_O01

I don't know why those are backwards from each other, but they've been that way since the move to github. Just doing a quick test swapping the 2.3.1 map to the 2.3 map seems to have the PipeParser.Parse return the message typed as ORM_O01.

**Comment by milkshakeuk** [comment]
@thestephenstanton do you have an example message?

**Comment by thestephenstanton** [comment]
@milkshakeuk it's been so long and I don't work with this repo anymore so I do not.

**Comment by milkshakeuk** [comment]
@thestephenstanton I don't think this is actually an issue anymore, looked at your original post and the event map for 231 no longer looks like that, in fact I thinks it was fixed in #107
